# Filename:str_advance.py

str1 = "my Name is Ching"
print("m count:" + str(str1.count("m")))
print("m find:" + str(str1.find("m")))
print("m index:" + str(str1.index("m")))
print("m rfind:" + str(str1.rfind("m")))
print("m rindex:" + str(str1.rindex("m")))

print("isalnum:" + str(str1.isalnum()))
print("isalpha:" + str(str1.isalpha()))
print("isdigit:" + str(str1.isdigit()))
print("istitle:" + str(str1.istitle()))
print("isspace:" + str(str1.isspace()))
print("islower:" + str(str1.islower()))
print("isupper:" + str(str1.isupper()))
print("split:" + str(str1.split()))
print("rsplit:" + str(str1.rsplit()))
print("join:" + str(str1.join("aaa")))
print("strip:" + str(str1.strip()))
print("replace:" + str(str1.replace('is',"are")))
print("capitalize:" + str(str1.capitalize()))
print("lower:" + str(str1.lower()))
print("upper:" + str(str1.upper()))
print("swapcase:" + str(str1.swapcase()))
print("title:" + str(str1.title()))
print("center:" + str(str1.center(30)))
print("ljust:" + str(str1.ljust(50)))
print("rjust:" + str(str1.rjust(50)))
