# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDjangoLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('age', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=50)),
                ('addtime', models.DateField(max_length=14)),
            ],
        ),
        migrations.DeleteModel(
            name='World',
        ),
    ]
